<a href="https://colab.research.google.com/github/GiselaCS/Mujeres_Digitales/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np 
import time

Numpy
Paquete fundamental para operaciones matematicas en Python

Link mayor info: https://numpy.org/

Ultima version: NumPy v1.20.0

NumPy es un proyecto de código abierto que tiene como objetivo permitir la computación numérica con Python. Fue creado en 2005, basándose en el trabajo inicial de las bibliotecas Numeric y Numarray. NumPy siempre será un software 100% de código abierto, de uso gratuito para todos y publicado bajo los términos liberales de la licencia BSD modificada.

NumPy se desarrolla al aire libre en GitHub, a través del consenso de NumPy y de la comunidad científica Python en general. Para obtener más información sobre nuestro enfoque de gobernanza, consulte nuestro Documento de gobernanza.

Equipo: https://numpy.org/gallery/team.html

NUMPY es un paquete fundamental para el trabajo de computacion cientifica con PYTHON, contiene

1. Tipos de datos
2. Clases
3. Funciones
4. Modulos

Estos pisibilitan la creacion y manejo de array n-dimensionales

El tipo de datos mas importante es el array (o ndarray, de n dimensiones)

Algunas ventajas:

1. Multiplataforma
2. Potente Tiene funcionalidades de 3. cualquier otro paquete numerico
3. Perfecta integracion interactuando con los tipos de datos y estructuras propios del lenguaje
4. Gratuito

In [2]:
#una lista de listas
#filas y columnas
a= np.array([[1,2,3],[4,5,6]])
print('a=', a)

a= [[1 2 3]
 [4 5 6]]


In [7]:
#cantidad de filas y columnas que tiene el arreglo
print(a.shape)

(2, 3)


In [4]:
# cuantos elementos tiene
print(a.ndim)

2


In [3]:
#tamaño del dato
print(a.size)

6


In [5]:
#tipo de dato
print(a.dtype)

int64


In [6]:
#trae los datos reales
print(a.real)

[[1 2 3]
 [4 5 6]]


In [8]:
#trae los elementos imaginarios
print(a.imag)

[[0 0 0]
 [0 0 0]]


In [9]:
# Arrays n dimensionales
a= np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]],dtype=int)
print(a.shape)
print(a)

(3, 4)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [12]:
#el primer numero es filas el segundo columnas
a.shape

(3, 4)

In [13]:
a.shape[0] #fila

3

In [11]:
a.shape[1] #columnas

4

**Manejo Basico**
---

1. Creacion
2. Indexacion
3. Operaciones aritmeticas (broadcasting) relacionale sy logicas
4. Cambio de tipo (Casting)
5. Valores especiales (nana o inf)
6. Creacion En principio 4 formas

A partir de secuencias (listas o tuplas) de PYTHON

1. Haciendo uso de funciones propias de numpy
2. Lectura de datos desde fichero
3. Copiando otro array
4. numpy.array(secuencia, tipo_datos)

In [14]:
'''
El casting es un procedimiento para transformar una variable primitiva de un tipo a otro. 
También se utiliza para transformar un objeto de una clase a otra clase siempre y cuando 
haya una relación de herencia entre ambas.
'''
import numpy 
#los convierte a string
a0=numpy.array([1,'5',4.3,1+3j]) # Casting implicito
print(a0)
print(type(a0[0]))
tupla=(3,5,7.7)
a2= numpy.array(tupla)
print(a2)
a3= numpy.array([])
print(a3)
a4=numpy.array(['lineal','lineal2','33'],dtype='|S3')
print(a4)

['1' '5' '4.3' '(1+3j)']
<class 'numpy.str_'>
[3.  5.  7.7]
[]
[b'lin' b'lin' b'33']


In [15]:
# Creacion con funciones numpy
#del 5 al 6 de 0.1 
numpy.arange(5,6,0.1)

array([5. , 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9])

In [16]:
numpy.linspace(5,6,5)
# Devuelve un array en el que se ha dividido el intervalo start, stop en num fragmentos

array([5.  , 5.25, 5.5 , 5.75, 6.  ])

In [17]:
# el .ones crea matrices llenas de 1
print(numpy.ones([2,3],dtype='int'))

[[1 1 1]
 [1 1 1]]


In [18]:
numpy.zeros #matrices con 0

<function numpy.zeros>

In [19]:
numpy.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [20]:
#ejemplo
a = numpy.array([[1,2],[3,4]])

In [21]:
a

array([[1, 2],
       [3, 4]])

In [23]:
#trae el elemento que se encuentra en esa posicion
a[0,1]

2

In [34]:
b= numpy.array([[1,5],[3,4]])
b

array([[1, 5],
       [3, 4]])

In [35]:
#este elemento tiene dos nombres
c=b


In [36]:
b[0,1]=2

In [37]:
#cualquier cambio se refleja en ambos
c

array([[1, 2],
       [3, 4]])

In [38]:
b

array([[1, 2],
       [3, 4]])


Los arrays n-diemnsionales se pueden modificar haciendo uso de la propiedad shape o del metodo reshape

In [39]:
numpy.ones((2,3))
a=numpy.ones(10)
print(a)
print(a.shape)
a.shape=[2,5]
print(a)
# Con el metodo reshape
a= numpy.ones(10)
print(a.shape)
b= a.reshape((2,5))
print(b)
print(b.shape)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
(10,)
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
(10,)
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
(2, 5)


Para arrays n dimensionales se usa la siguiente estructura:


Se hace referencia a cada elemento del array con tantos indices, separados por comas, como dimensiones tiene el array.
La combinación de indices va entre corchetes tras el nombre del array.
nombrearray[indexDim1,indexDim2,..., indexDimN]


El operador : sustituye a todo el rango de indices posibles en la dimension en la que aparece

In [41]:
#el arange es como un range, y con el reshampe se puede organizar los datos
numpy.arange(4).reshape((4,1)) #cuatro filas con una columna

array([[0],
       [1],
       [2],
       [3]])

In [40]:
a=numpy.linspace(0,1,5)
print(a)
print(a[:])
b=numpy.arange(4).reshape((2,2))
print(b)
print(b[:,1])
print(b[0,:])

[0.   0.25 0.5  0.75 1.  ]
[0.   0.25 0.5  0.75 1.  ]
[[0 1]
 [2 3]]
[1 3]
[0 1]


In [42]:
a=numpy.arange(24,dtype='int')
a=a.reshape((2,3,4))
print(a)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [50]:
#arreglo de solo 1 de (2,5), luego se de (5,2)
unos= numpy.ones([2,5])
unos


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [51]:
#cambiar de 5 a 2
unos= unos.reshape([5,2])
unos

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

AttributeError: ignored